//
//  MessagesRouter.swift
//  CleanSwiftSample
//
//  Created by Okhan Okbay on 24.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MessagesRoutingLogic: AnyObject {
  
}

protocol MessagesDataPassing {
  var dataStore: MessagesDataStoreProtocol { get }
}

final class MessagesRouter: MessagesRoutingLogic, MessagesDataPassing {
  
  let dataStore: MessagesDataStoreProtocol
  private weak var viewController: UIViewController!
  
  init(dataStore: MessagesDataStoreProtocol,
       viewController: UIViewController) {
    
    self.dataStore = dataStore
    self.viewController = viewController
  }
}
