//
//  LoginRouter.swift
//  CleanSwiftSample
//
//  Created by Okhan Okbay on 24.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginRoutingLogic: AnyObject {
  func routeToMessages()
}

protocol LoginDataPassing {
  var dataStore: LoginDataStoreProtocol { get }
}

final class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing {
  
  let dataStore: LoginDataStoreProtocol
  private weak var viewController: UIViewController!
  
  init(dataStore: LoginDataStoreProtocol,
       viewController: UIViewController) {
    
    self.dataStore = dataStore
    self.viewController = viewController
  }
  
  func routeToMessages() {
    let messagesViewController = MessagesViewController.loadFromNib()
    let messagesDataStore = messagesViewController.router.dataStore
    messagesDataStore.username = dataStore.username
    
    viewController.navigationController?.pushViewController(messagesViewController, animated: true)
  }
}
